### DISCUSSION TITLE
Separate identity and network files

### DISCUSSION THREAD

**Discussion by notassigned** [alecbcs/hyprspace#46] [Ideas]
I'm thinking we split a peer's identity into its own file and have a network file which is basically just a list of ip addrs -> peer IDs.

That way the same network definition file can be shared between them which would make configuration of larger networks easier.
e.g.

File: hs0.net
```
10.1.1.1:
    QmeZR8skL3v2amv1acFS7PEvz1w7hveHgLf4smGuX9KTjn
10.1.1.32:
    QmZqufDgzzsnur8Fx3ND1qbenseY9qE6TG2WUJRMUhvSnj
10.1.1.165:
    QmSrq3jnqGAja4z91Jq9SMQFJ8TzbRAgrMLi1sTR6Ane6W
10.1.1.49:
    QmfLMLGsdH63a6ktpEDZwQJNBYELf4RXhHGQFGgeQu8hHD
```
File: hs0.id 
(note self address is removed from here)
```
interface:
  name: hs0
  id: QmaeBwAD9cpjXzrYTtjuT6vjWqg9SAyGJDUwFNdcaveW7A
  listen_port: 8001
  discover_key: smartly-random-word-string
  private_key: !!binary |
      .....
```
