### DISCUSSION TITLE
IPNS/DNSLink as ID

### DISCUSSION THREAD

**Discussion by Winterhuman** [alecbcs/hyprspace#60] [Ideas]
# IPNS + DNSLink as Hyprspace IDs

## Intro

Currently, connecting to Hyprspace nodes requires writing out the PeerIDs like so...

**PEER A**
```
interface:
  name: hs0
  id: QmFoo...
...
peers:
  10.1.1.1:
    id: QmFoa...
```
**PEER B**
```
interface:
  name: hs0
  id: QmFoa...
  ...
peers:
  10.1.1.2:
    id: QmFoo...
```
This is tedious, but, also hard to avoid. The PeerID is derived from the private key, which is important to how IPFS even works, so we can't just derive a PeerID from a memorable string similar to how `discovery_key` worked.

*So, what could we do to avoid typing out the PeerID?*

## DNSLink

Pointing DNSLink to each node's PeerID is one possible solution, a TXT record pointing to `/ipns/PeerID` can be created which IPFS nodes can resolve (how Hyprspace should go about integrating DNS resolution is unknown to me), using DNSLink should mean this won't add any significant delay to discovery times. It'd look something like this:

**PEER A**
```
interface:
  name: hs0
  id: QmFoo...
...
peers:
  10.1.1.1:
    id: /ipns/peer2.domain.tld    [Create a TXT record stating '_dnslink.peer2.domain.tld -> QmFoa...']
```
**PEER B**
```
interface:
  name: hs0
  id: QmFoa...
  ...
peers:
  10.1.1.2:
    id: /ipns/peer1.domain.tld    [Create a TXT record stating '_dnslink.peer1.domain.tld -> QmFoo...']
```

### Advantages

- Reuses existing features and tools (DNSLink and IPNS resolving)
- Mimics Wireguard's ability to use domains as endpoints
- Won't add significant delay when using fast DNS servers

### Disadvantages

- Requires obtaining a domain and configuring DNSLink
